name: build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
    - name: Build estatisticas-estudantes-estruturado
      run: mvn -B package --file estatisticas-estudantes-estruturado/pom.xml
    - name: Build estatisticas-estudantes-funcional
      run: mvn -B package --file estatisticas-estudantes-funcional/pom.xml
    - name: Build projeto-base
      run: mvn -B package --file projeto-base/pom.xml
